version: "3"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000 #your PUID found with command id in your distro
      - PGID=1000 #your PGID found with command id in your distro
      - APP_URL= #your host URL:port
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASS= #your mariadb password
      - DB_DATABASE=bookstackapp
    volumes:
      - /home/eonloop/bookstack/config:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000 #your PUID found with command id in your distro
      - PGID=1000 #your PGID found with command id in your distro
      - MYSQL_ROOT_PASSWORD= #your MYSQL_ROOT_PASSWORD
      - TZ=Europe/Bucharest #your timezone
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD= #your mysql password
    volumes:
      - <your path>/dbconfig:/config
    restart: unless-stopped
